--- #YAML:1.0
name: Time-DayOfWeek
abstract: calculate which Day-of-Week a date is
version: 1.6.A6FFxZB
author:
  - Pip Stuart <Pip@CPAN.Org>
license: gpl
distribution_type: module
requires:
recommends:
build_requires:
  Test: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
urls:
  license: HTTP://FSF.Org/licensing/licenses/gpl.txt
meta-spec:
  version: 1.3
  url: HTTP://Module-Build.SourceForge.Net/META-spec-v1.3.html
generated_by: e pkg v1.0.A2RJrKV
